### ISSUE TITLE
Make file

### ISSUE THREAD

**Issue by gas-light** [christophebedard/instrument-attribute-gcc-plugin#27] opened 2021-07-20 03:28 UTC
Hi，I have done apt-get install -y gcc-7-plugin-dev, but I make fail.

root@nkg-002:/home/Repository/instrument-attribute-gcc-plugin# ls
**CONTRIBUTING.md  instrument_attribute.so  license-lgpl-v3.txt  Makefile   src   trace.sh
include          LICENSE                  license-mit.txt      README.md  test  utils.o**
root@nkg-002:/home/Repository/instrument-attribute-gcc-plugin# make
**make: Nothing to be done for 'all'.**
root@nkg-002:/home/Repository/instrument-attribute-gcc-plugin#

**Comment by christophebedard** [comment] 2021-07-20 15:45
I'm not sure what the problem is. It looks like you successfully built the plugin since you have this file: `instrument_attribute.so`

Running `make` after this won't do anything since you already ran `make` to build the plugin.

**Comment by christophebedard** [comment] 2021-07-24 15:12
I'll close this since there doesn't seem to be any issue.

**Closed by christophebedard** 2021-07-24 15:12 UTC
